sonar.projectKey=CristianMz21_prescriptions-app-frontend
sonar.organization=cristianmz21

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  node_modules/**,\
  coverage/**,\
  .next/**,\
  dist/**,\
  out/**,\
  build/**,\
  public/**,\
  *.config.js,\
  *.config.ts,\
  *.config.mjs,\
  next-env.d.ts

sonar.coverage.exclusions=\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/*.stories.ts,\
  **/*.stories.tsx,\
  **/types/**,\
  **/*.d.ts,\
  src/app/globals.css