import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  ArrowLeft,
  BarChart3,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CirclePlus,
  ClipboardList,
  Download,
  Eye,
  FileText,
  Home,
  Hospital,
  Inbox,
  Loader2,
  LogOut,
  Menu,
  Moon,
  Monitor,
  NotebookPen,
  Pill,
  Search,
  ShieldAlert,
  Sun,
  TrendingUp,
  UserCircle2,
  UserRound,
  Users,
  X,
} from "lucide-react";

export const ICON_REGISTRY = {
  activity: Activity,
  alertCircle: AlertCircle,
  arrowLeft: ArrowLeft,
  barChart3: BarChart3,
  check: Check,
  checkCircle2: CheckCircle2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circlePlus: CirclePlus,
  clipboardList: ClipboardList,
  download: Download,
  eye: Eye,
  fileText: FileText,
  home: Home,
  hospital: Hospital,
  inbox: Inbox,
  loader2: Loader2,
  logOut: LogOut,
  menu: Menu,
  moon: Moon,
  monitor: Monitor,
  notebookPen: NotebookPen,
  pill: Pill,
  search: Search,
  shieldAlert: ShieldAlert,
  sun: Sun,
  trendingUp: TrendingUp,
  userCircle2: UserCircle2,
  userRound: UserRound,
  users: Users,
  x: X,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof ICON_REGISTRY;
